### ISSUE TITLE
ForceTest.exe groves effect doesnt work as it should

### ISSUE THREAD

**Issue by SchmidtFranz** [jmriego/brunnerdx#1] opened 2021-02-17 00:34 UTC
Im using your library for my own custom ffb joystick, and currently have a test setup with a old ffb stick. Basic functions work great at the moment, but the groves effect in ForceTest.exe doesnt work as it should.
When playing the groves effect on MSFFB2 the time adjusts the spacing between the groves, but with your firmware implementation the time adjusts the time it takes for the effect to start after activating it in the program (example: spacing 700 the effect starts after 700ms and then its just fast vibration).
I previously used the code from YukMingLaw (it has the same problem) but that doesnt seam to be maintained as much as your repository.
I looked around a bit in the source code and i think the problem could be where the effects are read from the data that is send to ardiono from the pc and the subsquent interpretation of that, but all the USB HID stuff goes way above my head so it would be great if you could look into this.

**Comment by jmriego** [comment] 2021-02-18 16:54
glad to see this is used some other ways. I had to do something quite different to the code from YukMingLaw because I was finding some issues when using two axes so I just created a new fork.
Also I had the problem that for this particular device I had to make changes to reduce the memory usage.

The problem is that there's not such thing as a groove effect in DirectX but I guess it has to be the square effect. I have a MSFFB2 so I'll be able to check against as well. Thanks for the detailed description

Last weekend I fixed some issues around periodic effects. Did you check with the last version?
Anyway, I'll have a look at it this weekend. The part of the code that it's involved it's probably this:
https://github.com/jmriego/brunnerdx/blob/master/src/Joystick.cpp#L582

This page gives some idea of what magnitude means and some other variables:
https://docs.microsoft.com/en-us/previous-versions/windows/desktop/ee416225(v=vs.85)

**Comment by jmriego** [comment] 2021-02-22 19:30
hi @SchmidtFranz ,

I got something working around this. It was really difficult because it turns out the USB device didn't receive the time between bumps from Windows. The original developer for ForceTest.exe pointed me in the direction. It seems like there are other commercial devices out there with this issue.

I am going to split this project in two: [Fino](https://github.com/jmriego/Fino) for the Force Feedback Arduino library and sketch and I'm going to use this repo for a GUI I'm writing for the Brunner device.

Please have a look at the latest code in [Fino](https://github.com/jmriego/Fino) and let me know if this works for you. At the moment I have to start and stop the effect to get it to detect the updated spacing. Not sure if that's the same that happens with the MS FFB2

**Comment by SchmidtFranz** [comment] 2021-02-22 19:38
Jmriego, that's fantastic, I'm going to have a look at the new fino project next weekend, I have some bldc motors and foc controllers and encoders coming to test it out properly. Thanks for your work, I'm going to report back next weekend if I find any issues. I think it was the same with the msffb2 that you have to start and stop the effect for it to update.

**Comment by jmriego** [comment] 2021-03-14 21:10
fixed now! I've created a PR in the Fino repo. Closing this one for now

**Closed as completed by jmriego** 2021-03-14 21:10 UTC
